### ISSUE TITLE
`entire` is entirely misleading

### ISSUE THREAD

**Issue by drquicksilver** [fumieval/xml-lens#5]
I think that `entire` is greatly inclined to lead people down a false path.

Although the docs clearly say that it is an invalid traversal, they don't provide any guidance on what to use instead and what the safe ways are to use it. Having spent some time exploring xml-lens, here are my observations and proposals:

Observations:
1. `entire` is quite safe to use as a fold. It's quite safe to use it to alter attributes or the tag-name; but if you use it to try to change the nodes then you will generally erase all your work as the traversal closes off. For example `entire . el "foo"` looks like a great way to find all elements of tag `<foo>` and it works fine for read-only queries; i.e. it works fine used as a fold.  The brief example in the README doesn't use entire.
2. `deep (el "foo")`, using `deep` from `Control.Lens.Plated` works fine for queries and also for modifications. As the docs explain, it won't descend into successful matches, so it won't find nested `<foo>`.
3. `transform` works bottom-up and lets you modify even nested elements in a predictable way.

Proposal:
1. change `entire` from `Traversal' Element Element` to `Fold' Element Element`, which is completely safe. As a bonus, this already exists, it's `cosmos`.
2. add traversals for the tag-name and the attributes of every element because that _is_ a safe traversal. I think you could reasonably do `allNames :: Traversal' Element Name` and `allAttributes :: Traversal' Element (Map Name Text)`. Sometimes it might actually be more useful to have something which jointly traverses `(Name,Map Name Text)`.
3. document the fact that if you do want to make safe, global modifications you are best off using the functions from Plated which have already solved the modifying-yourself problem; in particular I would definitely point to `deep` which is very useful for finding elements anywhere in a document and `transform` for bottom-up transformation.

**Comment by fumieval** [comment]
Sorry for very late response. `entire` is now deprecated.

**Comment by fumieval** [comment]
Removed entire
